name: CI/CD Pipeline for ML Model

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Download Iris dataset (if not in the repo)
      - name: Download Iris Dataset from UCI
        run: |
          curl -o iris.csv https://raw.githubusercontent.com/rohit-2002/CICD-Project/master/iris.csv

      # Step 3: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else echo "requirements.txt not found"; fi

      # Step 5: Train the model
      - name: Train Model
        run: |
          if [ -f train_model.py ]; then python train_model.py; else echo "train_model.py not found"; exit 1; fi
